### ISSUE TITLE
Does dialign offline only support UTF-8 encoded input files?

### ISSUE THREAD

**Issue by mbauwens** [GuillaumeDD/dialign#4]
Hi @GuillaumeDD

We're trying out your `dialign` framework within the context of our research. Thanks for the contribution and the clear explanation in your 2021 paper 'Towards alignment strategies in human-agent interactions based on measures of lexical repetitions'!

We've run into an issue when running it offline via the CLI (`java -jar dialign.jar -i input -o output`) with the following error:

```
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at dialign.app.DialignOfflineApp$.$anonfun$main$3(DialignOfflineApp.scala:186)
        at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:75)
        at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
        at dialign.app.DialignOfflineApp$.main(DialignOfflineApp.scala:183)
        at dialign.app.DialignOfflineApp.main(DialignOfflineApp.scala)
```

After some trial and error (I have no experience with Scala), it turns out that this error was raised because the input files we used were in the ISO-8859-1 file encoding. Changing this to UTF-8 solved the error.

If files have to always be in the UTF-8 encoding, it might be good to include this information in the [Input Format](https://github.com/GuillaumeDD/dialign/tree/master/examples/dialign-offline#input-format) section of the Offline examples? Or are other encodings supported?

**Comment by GuillaumeDD** [comment]
Hi @mbauwens ,
Thank you :pray: for your interest in `dialign` and in the 2021 journal paper. I hope it will be helpful for your research work.

Thanks for the feedback about the encoding issue :+1:  Scala runs on top of the JVM which uses UTF-8 as the 
default encoding. It is possible to specify a different file encoding as follows:
```bash
java -Dfile.encoding=ISO-8859-1 -jar dialign.jar -i corpus/ -o output-dialign/
```
I've tried it on a toy example and it looks like it works. Let me know if that does not solve it on your side.

I have improved the documentation with some notes about encoding.

**Comment by mbauwens** [comment]
Thanks for the information! Seems rather simple, but I didn't have any previous experience with running Scala or jars for that matter. I can confirm that, on my machine, adding this flag also correctly sets up dialign to read files encoded in ISO-8859-1. The added documentation is also very clear 👍 Closing the issue.
